name: Build and Package ImageSplitter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 下载并解压 tkdnd（用于拖放功能）
      - name: Download and extract tkdnd
        run: |
          $tkdndUrl = "https://github.com/petasis/tkdnd/releases/download/tkdnd-release-test-v2.9.4-rc3/tkdnd-2.9.4-windows-x64.zip"
          Invoke-WebRequest -Uri $tkdndUrl -OutFile tkdnd.zip
          Expand-Archive -Path tkdnd.zip -DestinationPath tkdnd -Force

      # 5. 使用 PyInstaller 打包应用
      - name: Build with PyInstaller
        run: |
          pyinstaller `
            --onefile `
            --windowed `
            --icon=icon.ico `
            --add-data "icon.ico" `
            --add-data "tkdnd/*;tkdnd" `
            --hidden-import=ttkbootstrap `
            --hidden-import=pillow_heif `
            --clean `
            ImageSplitter.py

      # 6. 上传构建产物作为 Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageSplitter-build
          path: dist/ImageSplitter.exe

      # 7. 获取最新 Release 版本号（如果没有则从 1.0 开始）
      - name: Get latest release version
        id: get_version
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1, // 只获取最新的 Release
            });
            let version;
            if (response.data.length === 0) {
              version = '1.0'; // 如果没有 Release，从 1.0 开始
            } else {
              const latestTag = response.data[0].tag_name;
              const versionMatch = latestTag.match(/^(\d+)\.(\d+)$/);
              if (!versionMatch) {
                version = '1.0'; // 如果 tag_name 不符合规范，从 1.0 开始
              } else {
                // 递增版本号（例如 1.0 -> 1.1）
                const major = parseInt(versionMatch[1], 10);
                const minor = parseInt(versionMatch[2], 10) + 1;
                version = `${major}.${minor}`;
              }
            }
            // 使用环境文件设置输出
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `version=${version}\n`);

      # 8. 创建 Release 并上传构建产物
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }} # 使用动态生成的版本号
          name: ImageSplitter v${{ steps.get_version.outputs.version }} # Release 名称
          body: "Release of ImageSplitter v${{ steps.get_version.outputs.version }}" # Release 描述
          draft: false
          prerelease: false
          files: |
            dist/ImageSplitter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}